### ISSUE TITLE
Can JDK11  be used in IDEA as BootJdk?

### ISSUE THREAD

**Issue by cy1ng** [JetBrains/JetBrainsRuntime#1]
Excuse me , I just want to know whitch brach can I use to boot IDEA, I can compile jdk11 by myself,because I want to user ZGC In JDK11

**Comment by chrisvest** [comment]
JBR11 comes with ZGC since its in upstream HotSpot. You can go to Help -> Change Custom VM Options and add

```
-XX:+UnlockExperimentalVMOptions
-XX:+UseZGC
```

**Comment by RenGuotai** [comment]
为什么我加了这两个配置，IDEA无法启动了

**Comment by RenGuotai** [comment]
为什么添加这两个配置，IDEA无法启动? 我使用的是MacOs, IDEA版本是2020.3

**Comment by grsky360** [comment]
> 为什么添加这两个配置，IDEA无法启动? 我使用的是MacOs, IDEA版本是2020.3

mac在jdk14之后才支持ZGC
https://wiki.openjdk.java.net/display/zgc/Main#Main-SupportedPlatforms
