### ISSUE TITLE
Crash when reloading on `jbr_dcevm-17_0_1-osx-aarch64-b164.8`

### ISSUE THREAD

**Issue by mworzala** [JetBrains/JetBrainsRuntime#102]
When reloading using dcevm/hotswap agent on `jbr_dcevm-17_0_1-osx-aarch64-b164.8`, the reload happens and then the JVM crashes immediately. I have attached the crash report, let me know if any other information is helpful.

[hs_err_pid17685.log](https://github.com/JetBrains/JetBrainsRuntime/files/7689951/hs_err_pid17685.log)

**Comment by mworzala** [comment]
Hmm some more context, on a simpler project it does not crash but also does not apply the reloaded changes and prints
```
HOTSWAP AGENT: 22:34:47.539 ERROR (org.hotswap.agent.plugin.jdk.JdkPlugin) - classReload() exception No such field java.beans.Introspector.declaredMethodCache on null.
```
in the terminal. This error popped up on the original project as well.

**Comment by skybber** [comment]
You can ignore the HA error message. HA is not fully ported to java17 now. The crash seems more serious, is it reproducible?

**Comment by mworzala** [comment]
It’s consistent in one project, doesn’t happen in another. Although in the latter case nothing is reloaded as far as I can tell.

**Comment by skybber** [comment]
Is it possible to describe steps how to reproduce it on your `https://github.com/Minestom/Minestom` project?

**Comment by mworzala** [comment]
1. `git clone https://github.com/Minestom/Minestom`
2. `git checkout 529_extension_improvement`
3. (the rest in IntelliJ for convenience)
4. Project/gradle jdk to JBR
5. Debug `src/test/java/demo/Main` with `-XX:HotswapAgent=fatjar`
6. Make an edit at `src/main/java/net/minestom/server/instance/InstanceContainer#L465` (for example a system print)
7. Recompile/reload `InstanceContainer.java`
8. Crash

This is consistent on my machine. The crash does not seem consistent at other locations. That one always crashes though.

**Comment by skybber** [comment]
@mworzala thanks for great report. I've fix now for it, it should be included in next release.

**Comment by skybber** [comment]
@mworzala before patch will be available, you can use `-XX:-UseEmptySlotsInSupers ` as a workaround for your issue.

**Comment by mworzala** [comment]
Looks like that's working, thanks for the quick responses and patch!

I will close the issue for now, but if you could make a comment when the next release happens that would be great.

**Comment by avu** [comment]
@skybber why did you reopened this issue? Is it not fixed yet?
