### ISSUE TITLE
Random UI freezes with high CPU usage on macOS M1, sometimes crash

### ISSUE THREAD

**Issue by intellild** [JetBrains/JetBrainsRuntime#106]
OS: macOS 12.1
CPU: M1 Max
IDE: Webstorm

| Tried runtime                                | Behavior                                            |
| -------------------------------------------- | --------------------------------------------------- |
| JBR bundled with 2021.3                      | High CPU, random freeze, sometimes crash            |
| JBR 11_0_13-b1751.21                         | Same issue                                          |
| JBR bundled with 2021.2                      | More crashes than 2021.3                            |
| JBR bundled with 2020.3 boot 2021.3                     | Random freezes when git log opened, but has other bugs     |
| JBR 17_0_1-b164.8                            | Better than 2021.3, but still random freezes        |
| OpenJDK (Eclipse Temurin, formerly AdoptJDK) | Update: Random freezes when git log opened, font rendering is much worse than JBR |

I noticed that the high CPU usage occurs when I focus on the Webstorm window.
I observed similar high CPU for system built-in activity monitor, not sure if they are related.

**Comment by avu** [comment]
Thanks for reporting this. Could you provide some logs using Help->Diagnostic Tools->CPU Usage profiling

**Comment by intellild** [comment]
[WS-213.6461.79_intellild_30.12.2021_10.37.45.zip](https://github.com/JetBrains/JetBrainsRuntime/files/7791313/WS-213.6461.79_intellild_30.12.2021_10.37.45.zip)
@avu here is the snapshot

**Comment by intellild** [comment]
https://youtrack.jetbrains.com/issue/JBR-4119
