### ISSUE TITLE
How to get commit id of the release version 11.0.11+9-b1341.60

### ISSUE THREAD

**Issue by sunnysnowhi** [JetBrains/JetBrainsRuntime#107]
I want to know the commit id of an old release version, such as : 11.0.11+9-b1341.60
(https://confluence.jetbrains.com/pages/viewpage.action?pageId=218857477)

But I can not find any tag or banch which is same as this version.
How can I get the branch and commit id of this release version? 
Thank you very  much!

**Comment by sunnysnowhi** [comment]
anyone help ?

**Comment by NikitkoCent** [comment]
@sunnysnowhi Hey! Please check the [1341 branch](https://github.com/JetBrains/JetBrainsRuntime/commits/1341)

**Comment by avu** [comment]
Actually the version number contains the branch name. In your case (11.0.11+9-b1341.60) its  1341  (as was mentioned by @sunnysnowhi )
