### ISSUE TITLE
Release 17_0_1-b164.8 with IDEA 2021.3.2 menus cannot be clicked on MacOS

### ISSUE THREAD

**Issue by mustafaakin** [JetBrains/JetBrainsRuntime#110]
I use release 17_0_1-b164.8 on my Mac with M1 and for performance purposes, I'm using 17. I know it's not released yet, but if we update the IDEA to this version, (similar situation in other products) the menus on the top are not responsive, I see them clicked but nothing happens. Just wanted to let you know.

**Comment by wangxufire** [comment]
17_0_2-b315.1 same issue

**Comment by sy2nyk** [comment]
`jbScreenMenuBar.enabled=false`
in **idea.properties** solve this issue for me.

**Comment by mustafaakin** [comment]
The above fix works with the latest JBR.

**Comment by vprovodin** [comment]
@mustafaakin, @wangxufire Thanks for the report.
@sy2nyk thanks for the workaround

Could you please check if you have the following line  in your VM options file?
```
--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED
```
if it is not present then add it please

**Comment by gempir** [comment]
@vprovodin It wasn't in there, but now that I added it the menus work! Without the Workaround from @sy2nyk 

Full idea.vmoptions:

```
--illegal-access=warn
-Dsun.java2d.metal=true
--add-opens=java.desktop/java.awt.event=ALL-UNNAMED
--add-opens=java.desktop/sun.font=ALL-UNNAMED
--add-opens=java.desktop/java.awt=ALL-UNNAMED
--add-opens=java.desktop/sun.awt=ALL-UNNAMED
--add-opens=java.base/java.lang=ALL-UNNAMED
--add-opens=java.base/java.util=ALL-UNNAMED
--add-opens=java.desktop/javax.swing=ALL-UNNAMED
--add-opens=java.desktop/sun.swing=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.plaf.basic=ALL-UNNAMED
--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED
--add-opens=java.desktop/javax.swing.text.html=ALL-UNNAMED
--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED
--add-exports=java.desktop/sun.font=ALL-UNNAMED
--add-exports=java.desktop/com.apple.eawt=ALL-UNNAMED
--add-exports=java.desktop/com.apple.laf=ALL-UNNAMED
--add-exports=java.desktop/com.apple.eawt.event=ALL-UNNAMED
-Xmx3000m
```

**Comment by vprovodin** [comment]
@gempir thanks for the update. I am closing the issue
