### ISSUE TITLE
Wrong version string with jbr 17?

### ISSUE THREAD

**Issue by huyz-git** [JetBrains/JetBrainsRuntime#114]
On the release of jbr 17, the default configured version string is still `11.0.14`:
```
$ wget https://github.com/JetBrains/JetBrainsRuntime/archive/refs/tags/jbr17_0_2b315.1.tar.gz
$ tar xvf ./jbr17_0_2b315.1.tar.gz
$ cd JetBrainsRuntime-jbr17_0_2b315.1
$ ./configure
```
with output:
```
...
Configuration summary:
...
* Version string: 11.0.14-internal+0-adhoc.abc.JetBrainsRuntime-jbr1702b315.1 (11.0.14-internal)
...
```

Also, the file `make/autoconf/version-numbers` in the release tarball has the following:
```
DEFAULT_VERSION_FEATURE=11
DEFAULT_VERSION_INTERIM=0
DEFAULT_VERSION_UPDATE=14
```

So is there anything wrong with the version of jbr 17? How can I build jbr 17 with the right version, without explicitly overwrite version string with `--with-version-string` option?

**Comment by vprovodin** [comment]
It looks like the cause in the following - the repo contains both versions 11 and 17. We launch building 11 from master branch but 17 - from master17. In you case you got sources from master branch.
I see you got https://github.com/JetBrains/JetBrainsRuntime/archive/refs/tags/jbr17_0_2b315.1.tar.gz from the Assets section. Not sure that it is a proper way to get sources related to jbr17_0_2b315.1

If you need build jbr17 please follow the instruction in https://github.com/JetBrains/JetBrainsRuntime/tree/master17#readme

In particular
to get sources
```
% git clone git@github.com:JetBrains/JetBrainsRuntime.git
% cd JetBrainsRuntime/
```
to get sources related to development branch of JBR17
```
% git checkout master17
```
to get sources related to `jbr17_0_2b315.1` release
```
% git checkout 17_315
```
