### ISSUE TITLE
Would you like backport shenadoah gc for jdk 11?

### ISSUE THREAD

**Issue by cnmade** [JetBrains/JetBrainsRuntime#13]
Shenandoah is the low pause time garbage collector that reduces GC pause times by performing more garbage collection work concurrently with the running Java program. Shenandoah does the bulk of GC work concurrently, including the concurrent compaction, which means its pause times are no longer directly proportional to the size of the heap. Garbage collecting a 200 GB heap or a 2 GB heap should have the similar low pause behavior.

Which also backported for jdk 11.

http://hg.openjdk.java.net/shenandoah/jdk11/

**Comment by bric3** [comment]
I think this issue can be closed, Shenandoah is now available in latest jbr 11 releases.
