### ISSUE TITLE
Any reason why there are no recent jbr 17 binaries with DCEVM?

### ISSUE THREAD

**Issue by msievers** [JetBrains/JetBrainsRuntime#134]
Hi!

The latest jbr 17 release with pre-build binaries for DCEVM was 17_0_1.b164.8. See

https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr17_0_1b164.8

Since then, all jbr 17 releases don't show any DCEVM binaries anymore, for example also the latest one, please compare

https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr17.0.2b396.4

Is there any reason why there are no jbr_dcevm 17 binaries anymore?

**Comment by jsalts** [comment]
@skybber can you elaborate on how this actually works? I have the latest jbr17 running in debug mode in intellij and deleting / adding lambdas is not working. With the java11 devm jre, all I had to do was swap out the jvm. Am I missing anything?
