### ISSUE TITLE
win x86 build

### ISSUE THREAD

**Issue by fshp** [JetBrains/JetBrainsRuntime#14]
Are you planning to build for win x86?

**Comment by vprovodin** [comment]
Do you mean 11? - Yes. Moreover such build already exists. Currently it is under testing. We will publish it as soon as possible.

**Comment by netroby** [comment]
go go go

**Comment by vprovodin** [comment]
JBR 32-bit executables for Windows are available at https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-windows-x86#files
