### ISSUE TITLE
jcef failed in macOS 13 beta

### ISSUE THREAD

**Issue by xinkunZ** [JetBrains/JetBrainsRuntime#155]
this is the demo project, it works in windows
[jcef-demo.zip](https://github.com/JetBrains/JetBrainsRuntime/files/8918497/jcef-demo.zip)

works in windows with: [jbr_jcef-17.0.3-windows-x64-b469.12.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.3-windows-x64-b469.12.tar.gz)
failed with: [jbr_jcef-17.0.3-osx-aarch64-b469.12.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.3-osx-aarch64-b469.12.tar.gz)

logs here:

[error.log](https://github.com/JetBrains/JetBrainsRuntime/files/8918506/error.log)

**Comment by artemm-bochkarev** [comment]
Can't reproduce. Please, create issue in [youtack](https://youtrack.jetbrains.com/) if this problem is still actual
