### ISSUE TITLE
diz builds

### ISSUE THREAD

**Issue by nihil-admirari** [JetBrains/JetBrainsRuntime#164]
https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.4b469.44 has `_diz` releases for Linux and macOS (no `_diz` for Windows):
- jbrsdk_jcef-17.0.4-linux-x64-b469.44_diz.tar.gz
- jbrsdk_jcef-17.0.4-linux-x64-b469.44.tar.gz
- jbrsdk-17.0.4-osx-aarch64-b469.44_diz.tar.gz
- jbrsdk-17.0.4-osx-aarch64-b469.44.tar.gz

What are they?

**Comment by vprovodin** [comment]
diz-files contain debug symbols which are generated during the build
https://github.com/JetBrains/JetBrainsRuntime/blob/main/doc/building.md#native-debug-symbols
https://github.com/JetBrains/JetBrainsRuntime/blob/main/doc/building.md#configure-arguments-for-tailoring-the-build
