### ISSUE TITLE
Old JBR releases download links don't work

### ISSUE THREAD

**Issue by wsafonov** [JetBrains/JetBrainsRuntime#171]
Links provided in README.md for downloading older releases of JBR (for IDE 2021.1 - [11.0.11+9-b1341.60](https://confluence.jetbrains.com/pages/viewpage.action?pageId=218857477), 2020.3 - [11_0_11-b1145.115](https://confluence.jetbrains.com/pages/viewpage.action?pageId=219349001)) lead to a private confluence page, making it impossible to download those versions of JBR.

**Comment by vprovodin** [comment]
Here are the links to the latest JBR binaries targeted for IDEs 2021.1:
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_11-linux-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_11-linux-x86-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_11-windows-x86-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_11-linux-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_11-osx-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_11-osx-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_11-windows-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_11-linux-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_11-osx-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_11-osx-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_11-windows-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_11-linux-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_11-osx-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_11-osx-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_11-windows-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_11-linux-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_11-osx-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_11-osx-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_11-windows-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-test-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-test-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-test-x86-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-x64-fastdebug-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-linux-x86-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-aarch64-fastdebug-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-test-aarch64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-test-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-osx-x64-fastdebug-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-windows-test-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-windows-test-x86-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-windows-x64-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-windows-x64-fastdebug-b1341.60.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_11-windows-x86-b1341.60.tar.gz

**Comment by vprovodin** [comment]
@wsafonov Thanks for reporting this issue.
The links to binaries for 2021.1 were provided in the previous message.
As for 2020.3 the binaries were restored we are looking a way to upload them. So it is in progress...

**Comment by vprovodin** [comment]
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_10-linux-x86-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr-11_0_10-windows-x86-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_10-osx-aarch64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_10-osx-aarch64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_fd-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_10-osx-aarch64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jfx-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jfx-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jfx-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_10-osx-aarch64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbr_nomod-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-linux-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-linux-x64-fastdebug-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-linux-x86-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-osx-aarch64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-osx-aarch64-fastdebug-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-osx-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-osx-x64-fastdebug-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-windows-x64-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-windows-x64-fastdebug-b1145.115.tar.gz
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_10-windows-x86-b1145.115.tar.gz

**Comment by wsafonov** [comment]
@vprovodin thanks for providing all the links! I saw that these comments have been already linked from the README file. That resolves the issue from my perspective.
