### ISSUE TITLE
deepin V20.7  make error  jdk-17  

### ISSUE THREAD

**Issue by hbignlin** [JetBrains/JetBrainsRuntime#176]
Building target 'images' in configuration 'linux-x86_64-server-release'
Compiling 8 files for BUILD_TOOLS_LANGTOOLS
Warning: No SCM configuration present and no .src-rev
Parsing 2 properties into enum-like class for jdk.compiler
Compiling 7 properties into resource bundles for jdk.jshell
Compiling 16 properties into resource bundles for jdk.compiler
Compiling 13 properties into resource bundles for jdk.javadoc
Compiling 12 properties into resource bundles for jdk.jdeps
Compiling 127 files for BUILD_java.compiler.interim
Compiling 399 files for BUILD_jdk.compiler.interim
Compiling 229 files for BUILD_jdk.javadoc.interim
/data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/src/java.compiler/share/classes/javax/tools/ToolProvider.java:144: warning: [removal] AccessController in java.security has been deprecated and marked for removal
        return AccessController.doPrivileged(pa);
               ^
error: warnings found and -Werror specified
1 error
1 warning
make[3]: *** [CompileInterimLangtools.gmk:97: /data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/build/linux-x86_64-server-release/buildtools/interim_langtools_modules/java.compiler.interim/_the.BUILD_java.compiler.interim_batch] Error 1
make[2]: *** [make/Main.gmk:78: interim-langtools] Error 2

ERROR: Build failed for target 'images' in configuration 'linux-x86_64-server-release' (exit code 2) 

=== Output from failing command(s) repeated here ===
* For target buildtools_interim_langtools_modules_java.compiler.interim__the.BUILD_java.compiler.interim_batch:
/data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/src/java.compiler/share/classes/javax/tools/ToolProvider.java:144: warning: [removal] AccessController in java.security has been deprecated and marked for removal
        return AccessController.doPrivileged(pa);
               ^
error: warnings found and -Werror specified
1 error
1 warning

* All command lines available in /data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/build/linux-x86_64-server-release/make-support/failure-logs.
=== End of repeated output ===

No indication of failed target found.
Hint: Try searching the build log for '] Error'.
Hint: See doc/building.html#troubleshooting for assistance.

make[1]: *** [/data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/make/Init.gmk:315：main] 错误 2
make: *** [/data/home/binglinHe/Downloads/JetBrainsRuntime-jbr-dev-2021-04-22-07-00/make/Init.gmk:186：images] 错误 2

**Comment by NikitkoCent** [comment]
@hbignlin, hi! Please run `configure` with the `--disable-warnings-as-errors` flag.
