### ISSUE TITLE
Regression using transparent title bar in Runtime 17.0.4.1-b597.1

### ISSUE THREAD

**Issue by ctipper** [JetBrains/JetBrainsRuntime#177]
When a transparent title bar is enabled using the following properties, a combobox dropdown becomes detached from its' control when the JFrame is dragged by the user with the mouse.

```
.getRootPane().putClientProperty("apple.awt.transparentTitleBar", true);
.getRootPane().putClientProperty("apple.awt.windowTransparentTitleBarHeight", 54f);
```

I have posted a GIF to illustrate the effect. I am unable to attribute this exactly, either Jetbrains runtime (17.0.4.1-b597.1), OpenJDK or Flatlaf Dark look and feel (2.4)?

![combobox](https://www.e-conomist.me.uk/images/Screen%20Recording%202022-09-22%20at%2012.07.43.gif)

**Comment by vprovodin** [comment]
Thanks for reporting this issue.
What OS did you observe this issue on?

**Comment by ctipper** [comment]
I have identified that this happens with system look and feel, I suspect the report needs to be upstreamed

macOS 12 Monterey 12.5 iMac 4K 21.5" (Intel)

**Comment by vprovodin** [comment]
Thanks for reporting this issue.
Tracking its state was moved to YourTrack see  [JBR-4875](https://youtrack.jetbrains.com/issue/JBR-4875)
So this issue on github will be closed.
