### ISSUE TITLE
no windows build since 18 May ?

### ISSUE THREAD

**Issue by alain57** [JetBrains/JetBrainsRuntime#180]
Hi all,
don't know if there is a visual bug or some missing entries, but I don't find any JBR 17 release since 18 May.
the provided releases are only for linux or osx. 
Is this on purpose or is this an error ?

Thanks in advance for your answer.
Best regards,
Alain

**Comment by NikitkoCent** [comment]
@alain57, hi! Looks like the tables just don't fit in preview page. You need to open a chosen release to see the whole table.
