### ISSUE TITLE
An error occurred in remote development using IDEA（error=0, Failed to exec spawn helper）

### ISSUE THREAD

**Issue by Litway0517** [JetBrains/JetBrainsRuntime#232]
environment info
Local IDEA, 231.8109.175
Server IDEA, 231.8109.175
Server JDK, java version "1.8.0_301"
The local can successfully connect to the remote server and open the project. But the debug program reports an error in IDEA. Downgrading the server IDEA version to 2022.2 will solve the problem. Please fix the problem of the 2023 version.
![image](https://user-images.githubusercontent.com/110079512/233282743-793f868c-ce37-474b-a367-6730988492c8.png)

**Comment by quanbisen** [comment]
any solution?

**Comment by mkartashev** [comment]
The issues here are for the JetBrains Runtime, which is a fork of OpenJDK. In order to get help with IDEA, please file an [issue in youtrack](https://youtrack.jetbrains.com/issues/IDEA?u=1).
