### ISSUE TITLE
Release 17.0.7b953.1 -> Crash Markdown plugins

### ISSUE THREAD

**Issue by Zouhuo** [JetBrains/JetBrainsRuntime#234]
The new release (17.0.7b953.1) [under linux] does not allow the 'Markdown plugins' to work in jetbrains development products

**Comment by wujimin** [comment]
have the same problem  
occurs only in linux  

once the markdown file is opened, the ide disappears immediately.

**Comment by artemm-bochkarev** [comment]
@Zouhuo @wujimin please create issue in https://youtrack.jetbrains.com with detailed description of problem. What linux do you use? Please attach stacktrace of crash.

**Comment by wujimin** [comment]
https://youtrack.jetbrains.com/issue/CPP-33509/clion-idea-2023.1-Crash-Markdown-plugins

**Comment by Zouhuo** [comment]
The cause may be this::
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.ui.jcef.JBCefApp
Same thing happens in version 17.0.7b954.1

**Comment by Zouhuo** [comment]
Follow this issue at the following link:
https://youtrack.jetbrains.com/issue/CPP-33509/clion-idea-2023.1-Crash-Markdown-plugins
