### ISSUE TITLE
Propose to submit to SDKMan

### ISSUE THREAD

**Issue by tonycody** [JetBrains/JetBrainsRuntime#236]
[https://sdkman.io/jdks](https://sdkman.io/jdks)

SDKMan is a unified solution that uses JDKS from different vendors.

**Comment by mkartashev** [comment]
How does a JDK vendor apply?

**Comment by tonycody** [comment]
> How does a JDK vendor apply?

https://sdkman.io/install

**Comment by mkartashev** [comment]
We are going to consider publishing JBR through sdkman and possibly other venues as well.

**Comment by StefanLobbenmeierObjego** [comment]
This has been fixed in https://github.com/sdkman/sdkman-disco-integration/pull/13
