### ISSUE TITLE
IntelliJ EAP with JBR 17.0.7+7-1000.2-jce Fails to Start in Gitpod standard workspaces

### ISSUE THREAD

**Issue by akosyakov** [JetBrains/JetBrainsRuntime#237]
Hello,

We are encountering a problem with IntelliJ EAP 232.8296.17 Remote Development (JetBrainsRuntime 17.0.7+7-1000.2-jce) on https://gitpod.io#https://github.com/gitpod-samples/spring-petclinic. Specifically, this version hangs on startup in our standard Gitpod workspaces (8GB RAM, 30GB storage). Tools like jstack are hanging as well. However, it does function as expected when switched to our large workspaces.

We've discovered that manually downgrading the JetBrains Runtime (JBR) to version 17.0.7+10-829.16-jcef for the same IntelliJ distribution resolves the issue. This led us to trace the problem to the following JBR release: [17.0.7b979.4](https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.7b979.4).

This issue is unique to our standard workspaces on gitpod.io and hasn't been replicated in other environments. Initially, we suspected CPU rate limiting due to abuse detection, but subsequent investigations ruled this out.

We're continuing our investigation on our side, but any insights from the JetBrainsRuntime team would be greatly appreciated. Please let us know if additional information is required.

Thank you for your assistance.

**Comment by mkartashev** [comment]
The scenario you are describing sounds completely unfamiliar; we have never encountered anything like that. I can only give some generic guidance in this case.
Apart from `jstack`, you can also try to get the  thread dump by sending `SIGQUIT` to the java process (`kill -3`); see if that works.
When all the Java-based tools are hanging, I'd go with the native ones and try attaching with a native debugger like gdb. It is also worth trying to run some simpler Java applications with various versions of JBR and/or OpenJDK to see how those behave in the same environment.

**Comment by mkartashev** [comment]
> Does it give any clue?

Alas, no.

**Comment by akosyakov** [comment]
It was resolved.
