### ISSUE TITLE
anyone can fix this problem:fctix wrong position of input window

### ISSUE THREAD

**Issue by aohanhongzhi** [JetBrains/JetBrainsRuntime#239]
https://youtrack.jetbrains.com/issue/JBR-2460/Wrong-position-of-input-window-and-no-input-preview-with-fcitx-and-ubuntu-13.04

https://github.com/Bryan2333/JBR-IME-HiDPI-Fixed/blob/master/idea.patch

**Comment by NikitkoCent** [comment]
Hello! We didn't forget about it, just are still working on. The fix is being released soon, don't worry 😉

**Comment by Humengchao** [comment]
@NikitkoCent This problem has existed for many years, which version we can use jetbrains ide correctly with Chinese

**Comment by bb33bb** [comment]
to be honest , it's really a big problem for my normal work, Now i use vscode for my usual work.
even though i paied jetbrains.
