### ISSUE TITLE
when support java 21

### ISSUE THREAD

**Issue by yoa1226** [JetBrains/JetBrainsRuntime#246]
Hello everyone, this is a fantastic project, and I am very grateful. 
I am very curious to know Is there a plan to support Java 21?

**Comment by mkartashev** [comment]
Yes. Check out the `jbr21` branch in the repository: it is based on OpenJDK 21.

**Comment by vprovodin** [comment]
Also you may download 21 executables from e.g. https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-21b212.1
