### ISSUE TITLE
CAccessible registers property change listeners only with instances of java.awt.Component

### ISSUE THREAD

**Issue by m-sasha** [JetBrains/JetBrainsRuntime#248]
`sun.lwawt.macosx.CAccessible` has this weird code:

```
    private CAccessible(final Accessible accessible) {
        ...
        if (accessible instanceof Component) {
            addNotificationListeners((Component)accessible);
        }
    }

    public void addNotificationListeners(Component c) {
        if (c instanceof Accessible) {
            AccessibleContext ac = ((Accessible)c).getAccessibleContext();
            ac.addPropertyChangeListener(new AXChangeNotifier());
        }
    }
```

which means that it will only add a property change listener if the `Accessible` is a `java.awt.Component`.

In [Compose Multiplatform](https://github.com/JetBrains/compose-multiplatform-core) we'd prefer to not instantiate a `Component` for each `Accessible`.

**Comment by mkartashev** [comment]
Could you please elaborate on how would you prefer this to be solved?

Also, we do accept external contributions, as does the OpenJDK community, so a patch that fixes this is welcomed. You can submit it here, but preferably to https://github.com/openjdk/jdk, with which we synchronize regularly.

**Comment by m-sasha** [comment]
@mkartashev 
The constructor checks `accessible` for being an instance of `Component` and then `addNotificationListeners` immediatey casts it back to `Accessible`. There's just zero need for the check and cast to `Component`.

**Comment by NikitkoCent** [comment]
There is [JBR-6129](https://youtrack.jetbrains.com/issue/JBR-6129) (filed by @m-sasha), so let's close GH issue, ok?
I'll take a look at it soon.
