### ISSUE TITLE
'jlink', 'jpackage' are missing for packaging a Compose Desktop app

### ISSUE THREAD

**Issue by thagikura** [JetBrains/JetBrainsRuntime#256]
I couldn't package a Compose desktop app with the JBR saying 

```
Execution failed for task ':desktopApp:checkRuntime'.
> Failed to check JDK distribution: 'jlink', 'jpackage' are missing
JDK distribution path: <JBR_install_path>
```

Is it intended or is it an issue?

I tried following steps

```
$ export JAVA_HOME=<path_to_JBR>
$ git clone https://github.com/JetBrains/compose-multiplatform
$ cd compose-multiplatform/examples/widgets-gallery
$ ./gradlew :desktop:packageDistributionForCurrentOS
```

The JBR I used was https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.9b1087.3

**Comment by thagikura** [comment]
I may have downloaded a wrong JBR. Sorry about that

**Comment by zhendong008** [comment]
Which JBR did you use in the end?

**Comment by dmitry-oshurkov** [comment]
JBRSDK:
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.5-linux-x64-b750.29.tar.gz

**Comment by dmitry-oshurkov** [comment]
> Which JBR did you use in the end?

JBRSDK:
https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-21.0.5-linux-x64-b750.29.tar.gz
