### ISSUE TITLE
Support JDK 21?

### ISSUE THREAD

**Issue by ice1000** [JetBrains/JetBrainsRuntime#262]
JDK 21 is a new LTS!

**Comment by ice1000** [comment]
I found https://youtrack.jetbrains.com/issue/JBR-5855/migrate-to-JBR21

**Comment by vprovodin** [comment]
It is still in progress.
You are correct -  this activity is being tracked by the above YT ticket.

**Comment by ice1000** [comment]
> It is still in progress.

Thanks for the reply! Really appreciate this work!

**Comment by Coder02Aniket** [comment]
Looking forward to new JBR!!!!

**Comment by romanstingler** [comment]
> Looking forward to new JBR!!!!

Today I saw that java 21 is available officially 21.341

![image](https://github.com/JetBrains/JetBrainsRuntime/assets/5576250/4bc47f6c-faad-4791-aa00-468b2da86c24)
![image](https://github.com/JetBrains/JetBrainsRuntime/assets/5576250/3b775b0a-cba7-462c-a015-d5c368aef11c)

**Comment by ice1000** [comment]
Nice!

**Comment by ice1000** [comment]
It would be interesting to see if virtual threads can bring any benefit to IntelliJ platform

**Comment by mkartashev** [comment]
> It would be interesting to see if virtual threads can bring any benefit to IntelliJ platform

The platform already uses Kotlin coroutines extensively, so I wouldn't expect any effect from the presence of virtual threads' implementation.

**Comment by ice1000** [comment]
Closed because the YouTrack ticket has been closed!
