### ISSUE TITLE
where is the src.zip

### ISSUE THREAD

**Issue by nzomkxia** [JetBrains/JetBrainsRuntime#282]
I cannot find the src.zip package in the released version, which makes it impossible to debug the JDK source code. Is there a solution to this issue?

**Comment by mkartashev** [comment]
> I cannot find the src.zip package in the released version, which makes it impossible to debug the JDK source code. Is there a solution to this issue?

Which released version specifically? I just tried one at random (`jbrsdk-21.0.2-linux-x64-b346.3`) and `src.zip` is there:
```
$ tar tzvf  ../jbrsdk-21.0.2-linux-x64-b346.3.tar.gz | ag src.zip
-rw-r--r-- 0/0        53684573 2024-01-25 17:06 jbrsdk-21.0.2-linux-x64-b346.3/lib/src.zip
```

**Comment by nzomkxia** [comment]
> > I cannot find the src.zip package in the released version, which makes it impossible to debug the JDK source code. Is there a solution to this issue?
> 
> Which released version specifically? I just tried one at random (`jbrsdk-21.0.2-linux-x64-b346.3`) and `src.zip` is there:
> 
> ```
> $ tar tzvf  ../jbrsdk-21.0.2-linux-x64-b346.3.tar.gz | ag src.zip
> -rw-r--r-- 0/0        53684573 2024-01-25 17:06 jbrsdk-21.0.2-linux-x64-b346.3/lib/src.zip
> ```

version is: [jbr_dcevm-11_0_12-osx-x64-b1504.37.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_12-osx-x64-b1504.37.tar.gz) from [this](https://github.com/JetBrains/JetBrainsRuntime/releases?page=11) page

**Comment by mkartashev** [comment]
We publish two kinds of packages: for running Java programs (JBR) and for developing Java programs (JBRSDK). The size of the former is kept to a minimum in order to reduce download time, so the source code and other things like demo programs are not included.
Unfortunately, the JBRSDK for the older version you are using were not published in the osx-x64 flavor.

**Comment by nzomkxia** [comment]
does JBRSDK here [jbrsdk-11_0_12-osx-aarch64-b1504.37.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk-11_0_12-osx-aarch64-b1504.37.tar.gz) include dcevm feature？

**Comment by vprovodin** [comment]
You may find it on https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jb11_0_12-b1504.37:

[jbr_dcevm-11_0_12-osx-aarch64-b1504.37.tar.gz](https://cache-redirector.jetbrains.com/intellij-jbr/jbr_dcevm-11_0_12-osx-aarch64-b1504.37.tar.gz)

**Comment by vprovodin** [comment]
nope.
