### ISSUE TITLE
This file is not the one used while building the shared archive file (modules)

### ISSUE THREAD

**Issue by rubin55** [JetBrains/JetBrainsRuntime#285]
I just upgraded to `jbrsdk_jcef-21.0.2-linux-x64-b346.3.tar.gz`. When running `java -version`, I'm seeing warnings in the output:

```shell
# java -version
[0.020s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.020s][warning][cds] This file is not the one used while building the shared archive file: /usr/lib/jvm/java-21-jetbrains/lib/modules
[0.020s][warning][cds] /usr/lib/jvm/java-21-jetbrains/lib/modules size has changed.
openjdk version "21.0.2" 2024-01-16
OpenJDK Runtime Environment JBR-21.0.2+13-346.3-jcef (build 21.0.2+13-b346.3)
OpenJDK 64-Bit Server VM JBR-21.0.2+13-346.3-jcef (build 21.0.2+13-b346.3, mixed mode)
```

**Comment by vprovodin** [comment]
This issue is being observed on _jbrsdk_jcef_ artefacts only and tracked by [JBR-6246](https://youtrack.jetbrains.com/issue/JBR-6246/default-CDS-archive-is-not-included-into-JBR-binaries).

It is a result of the integration JCEF into JBR. Unfortunately we have not overcome this issue yet...

**Comment by CelDaemon** [comment]
> It is a result of the integration JCEF into JBR. Unfortunately we have not overcome this issue yet...

I'm encountering this issue even with the default JBRSDK that shouldn't contain JCEF, the linked issue doesn't mention that as far as I know.

**Comment by mkartashev** [comment]
@CelDaemon Could you specify the exact version of that JBRSDK? We may be dealing with two issues here.

**Comment by CelDaemon** [comment]
> @CelDaemon Could you specify the exact version of that JBRSDK? We may be dealing with two issues here.

Of course, the archive of the version I'm using is `jbrsdk-21.0.2-linux-x64-b346.3.tar.gz`

**Comment by mkartashev** [comment]
Thanks! Indeed, same problem there:
```
$ ./jbrsdk-21.0.2-linux-x64-b346.3/bin/java -jar .../J2Ddemo/J2Ddemo.jar

[0.010s][warning][cds] This file is not the one used while building the shared archive file: /.../jbrsdk-21.0.2-linux-x64-b346.3/lib/modules
```

**Comment by mkartashev** [comment]
For the time being, a workaround is to either delete the CDS (class data sharing) archives 
```
$ rm lib/server/*.jsa
```
or re-generate them
```
$ ./bin/java -Xshare:dump
```
See https://docs.oracle.com/en/java/javase/17/vm/class-data-sharing.html for more info.

**Comment by CelDaemon** [comment]
> For the time being, a workaround is to either delete the CDS (class data sharing) archives

Thank you, that indeed fixed the issue!

**Comment by mkartashev** [comment]
This issue should've been fixed. Please, refer to [JBR-6246](https://youtrack.jetbrains.com/issue/JBR-6246) for all details.
