### ISSUE TITLE
linux系统中文输入法输入框不跟随

### ISSUE THREAD

**Issue by Jial08** [JetBrains/JetBrainsRuntime#32]
在Linux系统下安装了搜狗输入法，使用过程中输入法显示框不跟随，一直在左下角，使用 https://github.com/prehonor/myJetBrainsRuntime 重新编译运行环境可以解决该问题，希望能改进该问题，万分感谢！

**Comment by dekonoplyov** [comment]
Hi, thanks for feedback! 
There is an issue on YouTrack for this problem https://youtrack.jetbrains.com/issue/JBR-2460

**Comment by openalmeida** [comment]
Reproducible on IDEA 2020.2 of Linux 5.7. I've uppgrade to jbrsdk-11.0.8-b1031.1 (newest version currenly) but not solved.

one more thing:

apply option "-Drecreate.x11.input.method=true" is required, otherwize IME for Chinese mode is weird (almost useless).

**Comment by arfaWong** [comment]
@dekonoplyov This problem existed seven years ago, why hasn't it been fixed yet?

**Comment by dejin0916** [comment]
@dekonoplyov This page did not help,and as arfaWong sayes,his problem existed seven years ago, why hasn't it been fixed yet?

**Comment by Theswq** [comment]
按照这个 https://blog.csdn.net/u011166277/article/details/106287587可 以解决输入法不跟随的问题

**Comment by Jial08** [comment]
> 按照这个 https://blog.csdn.net/u011166277/article/details/106287587 可以解决输入法不跟随的问题

感谢回复，我在开始的时候就提到了解决方法，就是你提到的链接的作者发布的 github 地址，我是希望官方能够参考这些改动修改在自带编译环境中，而不要我们手动编译。

**Comment by wlnirvana** [comment]
有开发者做了一个自动编译项目 https://github.com/RikudouPatrickstar/JetBrainsRuntime-for-Linux-x64

可以在releases中下载，文件挺大的，但起码不再需要自己编译了

**Comment by dreamlu** [comment]
弃坑了，终极解决方案：使用[vscode](https://code.visualstudio.com/download)

**Comment by avu** [comment]
Please follow https://youtrack.jetbrains.com/issue/JBR-2460

**Comment by bjzhush** [comment]
a rebarbative bug
