### ISSUE TITLE
How is the full screen title bar hidden in the MacOS system implemented? It seems to be related to runtime, please see the picture. This issue has been bothering me for a long time

### ISSUE THREAD

**Issue by lwlha** [JetBrains/JetBrainsRuntime#327]
Case 1: When I use bundle running, after full screen:
![WechatIMG119](https://github.com/JetBrains/JetBrainsRuntime/assets/33903129/83f70cea-edf1-45c1-8fcf-7019b8c4e3e3)

Case 2: When I use this runtime, the title bar becomes floating after full screen display:
<img width="899" alt="截屏2024-03-05 09 48 44" src="https://github.com/JetBrains/JetBrainsRuntime/assets/33903129/5f1ac0c2-899f-40eb-afb2-77da6600a731">

I think the title bar implementation of case1 is currently the most perfect for non native applications. What should I do if I want to use it in my own Java GUI application?

**Comment by YaaZ** [comment]
@lwlha custom title bar is controlled via JBR API, I explained how to build and use it in anouther thread (#185). Please see `com.jetbrains.WindowDecorations.CustomTitleBar` class and related javadoc.
