### ISSUE TITLE
What's the relationship between github's release and `confluence.jetbrains.com`'s release?

### ISSUE THREAD

**Issue by huyz-git** [JetBrains/JetBrainsRuntime#36]
On github, the latest release of JBR 11.0.8 is `jb11_0_8-b92`, `jb11_0_8-b1`, `jb11_0_8-b1094`, `jb11_0_8-b34`.
On [confluence page](https://confluence.jetbrains.com/display/JBR/JetBrains+Runtime) it said that the latest release is `1094.1`.
On [bintray page](https://bintray.com/jetbrains/intellij-jbr/jbrsdk11-linux-x64) it said that the latest release is `1094.1`, `944.34`, `1071.1`.
The bundled JBR in `pycharm 2020.2` is `11.0.8+10-b944.31`.
On github, I can't find something like `jb11_0_8-b944`, only `jb11_0_7-b944`.

So what's the relationship between these releases?

**Comment by avu** [comment]
@huyz-git github provides all the major releases for all versions and all products. On confluence the information is organised by particular release version
