### ISSUE TITLE
JBR Custom Window Decoration problem

### ISSUE THREAD

**Issue by amir1376** [JetBrains/JetBrainsRuntime#362]
There is a problem in the `JBR` custom window decoration!
When you drag screen from top left of the IDE, the default window decoration will appear (double decorations, default and custom) and also the window borders will be gone too!

### Steps to reproduce::

1. Maximize the IDE"s Window
2. On the top left (near the IDE"s icon) of the custom window decoration start drag the window (just as much as quit the maximezed mode)
3. You will see the default windows decoration appears up to the custom decoration

Here is the result in `Windows OS and IntelliJ IDEA 2024.1`

![image](https://github.com/JetBrains/JetBrainsRuntime/assets/38394888/6275ccd0-c933-46ea-85b2-4f4dc938a11e)

**Comment by vprovodin** [comment]
@YaaZ Could you please take a look at this issue?
