### ISSUE TITLE
What's the difference between Bintray's binary distributions?

### ISSUE THREAD

**Issue by nihil-admirari** [JetBrains/JetBrainsRuntime#40]
Hi.

[Bintray](https://bintray.com/package/files/jetbrains/intellij-jbr/jbrsdk11-linux-x64) has multiple packages for the same build:
- `jbr-11_0_8-linux-x64-b1129.2.tar.gz`;
- `jbr_dcevm-11_0_8-linux-x64-b1129.2.tar.gz`;
- `jbr_fd-11_0_8-linux-x64-b1129.2.tar.gz`;
- `jbr_jcef-11_0_8-linux-x64-b1129.2.tar.gz`;
- `jbr_jfx-11_0_8-linux-x64-b1129.2.tar.gz`;
- `jbr_nomod-11_0_8-linux-x64-b1129.2.tar.gz`.

As far as I can tell:
- `nomod` is vanilla JRE;
- `jfx` is JRE + JavaFX;
- `jcef` is JRE + Java Chromium Embedded Framework;
- unqualified TAR is JRE + JavaFX + JCEF;
- `dcevm` is JRE + JCEF + Dynamic Code Evolution VM (class hotswap), but without JavaFX.

What `fd` stands for? Its module list is the same as in `jcef`, but binaries have different hashes.

JCEF and JavaFX are used by IDEA to e.g. render Markdown. If I prefer JCEF renderer, would a version without JavaFX be sufficient, or it is used by other parts of IDEA?

**Comment by vprovodin** [comment]
`fd` is fastdebug binaries

BTW In the latest release notes for 2020.2 e.g. https://confluence.jetbrains.com/pages/viewpage.action?pageId=190513155 you can see the _Downloads_ table with various binaries, it contains links to Bintray - unfortunately it have not contained links to fd tarballs.
Release notes for 2020.3 are pending

**Comment by nihil-admirari** [comment]
Ok. Page you referenced says JBR + JCEF is bundled by default, which means that JavaFX is really not necessary for IDEA to function. Closing the issue.
