### ISSUE TITLE
No GUI is being shown when running ItelliJ Idea 2024.1 on Debian 12 (WSL2)

### ISSUE THREAD

**Issue by cruiztorresj** [JetBrains/JetBrainsRuntime#432]
Yeah, sorry for posting this issue over here but I wasn't able to find the webform for posting it over the community edition repository.

So basically I am unable to run intelliJ Idea 2024.1 on Debian 12 (WSL2), I mean it is running but no graphical user interface is presented while doing so, which is weird because when I installed the software for the first time it worked like a charm. Here's a screenshot of what's on the screen.

![Screenshot 2024-08-06 181935](https://github.com/user-attachments/assets/d6a9edd5-6e14-4c76-8afc-10fa7390ad58)

If you need further information please let me know.

Hope this post collaborate so you can improve even further the experience for all your users.

P.S. I already posted a similar issue in the WSL2 github repository.

**Comment by cruiztorresj** [comment]
Found this workaround.
Hopefully it helps someone.

**Comment by mkartashev** [comment]
> Found this workaround.

What's the workaround?

**Comment by cruiztorresj** [comment]
> > Found this workaround.
> 
> What's the workaround?

This command `wsl --shutdown` in a power shell console, or another tab in Windows Terminal. It is not ideal but all the GUI software started appearing on the screen. Of course you will have to open again another tab (or window) with Debian 12.

Hope that helps
