### ISSUE TITLE
how to use zgc in DCEVM

### ISSUE THREAD

**Issue by nzomkxia** [JetBrains/JetBrainsRuntime#483]
JBR-17.0.2+8-396.4 in linux
![image](https://github.com/user-attachments/assets/fc06f9a3-b64d-4c0e-bc47-998aad23a74d)

**Comment by skybber** [comment]
Unfortunately ZGC is not supported with `-XX:+AllowEnhancedClassRedefinition`

**Comment by nzomkxia** [comment]
@skybber  any plan to support it?

**Comment by skybber** [comment]
At the moment, there isn’t a specific plan for this. Could you please share more about your use case? Is G1 not meeting your requirements?

**Comment by nzomkxia** [comment]
thanks,  G1 is enough for application development.

**Comment by ShayBox** [comment]
Is there any update on this? It's 3/4th through the year.  
This would be really useful for Minecraft development.

**Comment by skybber** [comment]
Yes, it’s still on our roadmap for this year. We don’t have a more specific timeline to share yet, but it’s definitely still planned.
