### ISSUE TITLE
Linux Wayland support

### ISSUE THREAD

**Issue by iMonZ** [JetBrains/JetBrainsRuntime#57]
JBR currently doesn’t support native Wayland.
Are there any plans of supporting it?

**Comment by vprovodin** [comment]
Could you please follow to https://youtrack.jetbrains.com/issue/JBR-1315

**Comment by gilvbp** [comment]
Any updates?

**Comment by NikitkoCent** [comment]
@gilvbp it's in-progress, but there's no ETA. Please follow https://youtrack.jetbrains.com/issue/JBR-3206 for recent information

**Comment by devurandom** [comment]
See-also: https://github.com/JetBrains/JetBrainsRuntime/issues/242
