### ISSUE TITLE
Where can I download the binary JBR

### ISSUE THREAD

**Issue by echopairs** [JetBrains/JetBrainsRuntime#69]
https://bintray.com/jetbrains/intellij-jdk/   Jump to https://jfrog.com/center-sunset/

**Comment by vprovodin** [comment]
JBR releases will be accessible via https://github.com/JetBrains/JetBrainsRuntime/releases
The latest release, which is targeted for IDEA 20211.2, is https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jb11_0_11-b1504.8

**Comment by echopairs** [comment]
> JBR releases will be accessible via https://github.com/JetBrains/JetBrainsRuntime/releases
> The latest release, which is targeted for IDEA 20211.2, is https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jb11_0_11-b1504.8

Thanks for your reply. I would also like to ask whether the latest JBR can be adapted to the previous version. For example, 2020.2.4 can also use JBR JB11_0_11-B1504.8
