### ISSUE TITLE
Switch to Java 17?

### ISSUE THREAD

**Issue by dragonejt** [JetBrains/JetBrainsRuntime#85]
Are there any plans to switch the JetBrains Runtime version from 11 to the new LTS version 17 in the future?

Or is JetBrains going to stick with 11 for the forseeable future?

**Comment by treyperry** [comment]
@dragonejt They're actively doing it. Check out the `master17` branch. Incidentally, it includes support for the Metal framework on MacOS, which improves display performance if you're using a Mac.
