### ISSUE TITLE
IDEA2021.2.3 debug stucked on arm mac useing JbR17 

### ISSUE THREAD

**Issue by youdmeng** [JetBrains/JetBrainsRuntime#91]
when i start，it`s show like this:
<img width="718" alt="截屏2021-10-23 08 55 41" src="https://user-images.githubusercontent.com/38751158/138536251-b37487dd-6391-42c6-919e-3f9f1b43851b.png">

when i press the stop button,it`s show like this:
<img width="1670" alt="截屏2021-10-23 09 00 29" src="https://user-images.githubusercontent.com/38751158/138536324-a1aa4357-21d0-47c8-a08f-7d60e8c7a7bc.png">

**Comment by fengjx** [comment]
me too
