### ISSUE TITLE
JBR- 11.0.11+9-b1341.60 Cause display problems

### ISSUE THREAD

**Issue by yuanqizhe** [JetBrains/JetBrainsRuntime#97]
When use the inner JBR- 11.0.11+9-b1341.60

（https://confluence.jetbrains.com/pages/viewpage.action?pageId=218857477）, There are some exceptions in the theme display. Icons do not have transparent background.

The machine environment:

Runtime version: 11.0.11+9-b1341.60 amd64

VM: Dynamic Code Evolution 64-Bit Server VM by JetBrains s.r.o.

Linux 4.15.0-153-generic

 

The IDE Version 2021.2.3,Latest JBR 11.0.11+9-b1341.60

 

All icons have opaque background:
![2](https://user-images.githubusercontent.com/44384957/142097119-0e6b0c05-5f9d-4231-92fd-1dad5891bb86.png)

**Comment by mkartashev** [comment]
This is a known side-effect of a remote X session workaround discussed at length in this [support article](https://intellij-support.jetbrains.com/hc/en-us/articles/4403466097042). It should no longer be needed in the next [version of IDEs](https://www.jetbrains.com/idea/nextversion/).
